version: '3'

services:
    mariadb:
        image: mariadb:latest
        ports:
            - 3306:3306
        volumes:
            - ./sql:/app
            - ./log:/var/log/mysql
            - ppddb:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'ppduser'
            MYSQL_PASSWORD: 'ppdpwd'
            MYSQL_DATABASE: 'ppddb'

volumes:
    ppddb:
